apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gifverse-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/client-max-body-size: "15m"
spec:
  rules:
  - host: gifverse.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gifverse-service
            port:
              number: 80
